# Generated by Django 3.0.6 on 2020-08-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200814_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='009043959395', max_length=20),
            preserve_default=False,
        ),
    ]
